name: Add to Current Team Activity 

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/anderson-optimization/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECTS_PAT }}