name: 'Stale Issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECTS_PAT }}
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-close: -1
          stale-issue-message: 'GH Action: This issue is stale because it has been open 30 days with no activity.'
          stale-pr-message: 'GH Action: This PR is stale because it has been open 45 days with no activity.'
          stale-issue-label: 'Status: Stale'
          stale-pr-label: 'Status: Stale'